# Generated by Django 4.2.17 on 2025-01-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='web.category')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='20250120100533', max_length=100)),
                ('concession_category', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_mode', models.CharField(max_length=4, null=True)),
                ('thali_type', models.CharField(blank=True, max_length=20, null=True)),
                ('thali_type_name', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item1', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item1_name', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item2', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item2_name', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item3', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item3_name', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item4', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item4_name', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thali',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('long_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.CharField(default='20250120100533', max_length=100)),
                ('transaction', models.CharField(max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='web.customer')),
            ],
            options={
                'unique_together': {('mobile', 'transaction_time')},
            },
        ),
    ]
