# Generated by Django 4.2.17 on 2025-01-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='transaction',
            new_name='particulars',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20250120120723', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_time',
            field=models.CharField(default='20250120120723', max_length=100),
        ),
    ]
