# Generated by Django 5.1.4 on 2025-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
