# Generated by Django 5.1.4 on 2025-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_long_name_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=4)),
                ('category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='20250104154852', max_length=100)),
                ('concession_category', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('thali_type', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item1', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item2', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item3', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_item4', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(default='20250104154852')),
                ('transaction', models.CharField(max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
