# Generated by Django 5.1.4 on 2025-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_concession_order_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='mobile',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20250104155326', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_time',
            field=models.DateTimeField(default='20250104155326'),
        ),
    ]
